[[language]]
name = "c"
formatter = { command = "clang-format", args = [ "--style=file", "--assume-filename=.c", "--fallback-style=WebKit"] }
auto-format = true

[[language]]
name = "kotlin"
# formatter = { command = "ktfmt", args = [ "--kotlinlang-style", "-" ] }
auto-format = true

[[language]]
name = "java"
formatter = { command = "clang-format", args = [ "--style=file", "--assume-filename=.java", "--fallback-style=Google"] }
auto-format = true

[[language]]
name = "groovy"
language-servers = [ "groovy-language-server" ]

[language-server.groovy-language-server]
command = "groovy-language-server"

[language-server.kotlin-language-server]
config = { provideFormatter = true }
